<?php
/**
 * Creative Popup - https://creativepopup.webshopworks.com
 *
 * @author    WebshopWorks <info@webshopworks.com>
 * @copyright 2018-2024 WebshopWorks
 * @license   One Domain Licence
 *
 * Not allowed to resell or redistribute this software
 */
if (!defined('_PS_VERSION_')) {
    exit;
}
?>
<script type="text/html" id="cp-static-layer-item-template">
    <li>
        <a href="#" class="dashicons dashicons-redo cp-icon-jump" data-help="<?php cp_e('Click this icon to jump to the page where this layer was added on, so you can quickly edit its settings.'); ?>"></a>
        <div class="cp-sublayer-thumb"></div>
        <span class="cp-sublayer-title"><?php echo sprintf(cp__('Layer #%d'), '1'); ?></span>
    </li>
</script>
