<?php
/**
 * Prestashop module : OpartStat
 *
 * @author Olivier CLEMENCE <manit4c@gmail.com>
 * @copyright  Op'art
 * @license Tous droits réservés / Le droit d'auteur s'applique (All rights reserved / French copyright law applies)
 */

if (!defined('_PS_VERSION_')) {
    exit;
}

function upgrade_module_1_0_29($module)
{
    $result = true;

    $result &= Db::getInstance()->execute(
        'CREATE TABLE IF NOT EXISTS `' . _DB_PREFIX_ . 'opartstat_robots` (
            `robotId` int(10) NOT NULL AUTO_INCREMENT,
            `name` varchar(250),
            PRIMARY KEY (`robotId`)
            ) ENGINE=' . _MYSQL_ENGINE_ . ' DEFAULT CHARSET=utf8'
    );

    $result &= Db::getInstance()->execute(
        'INSERT INTO `' . _DB_PREFIX_ . 'opartstat_robots` (name) VALUES 
        ("BotLink"),
        ("ahoy"),
        ("AlkalineBOT"),
        ("anthill"),
        ("appie"),
        ("arale"),
        ("araneo"),
        ("AraybOt"),
        ("ariadne"),
        ("arks"),
        ("ATN_Worldwide"),
        ("Atomz"),
        ("bbot"),
        ("Bjaaland"),
        ("Ukonline"),
        ("borg-bot/0.9"),
        ("boxseabot"),
        ("bspider"),
        ("calif"),
        ("christcrawler"),
        ("CMC/0.01"),
        ("combine"),
        ("confuzzledbot"),
        ("CoolBot"),
        ("cosmos"),
        ("Internet Cruiser Robot"),
        ("cusco"),
        ("cyberspyder"),
        ("cydralspider"),
        ("desertrealm, desert realm"),
        ("digger"),
        ("DIIbot"),
        ("grabber"),
        ("downloadexpress"),
        ("DragonBot"),
        ("dwcp"),
        ("ecollector"),
        ("ebiness"),
        ("elfinbot"),
        ("esculapio"),
        ("esther"),
        ("fastcrawler"),
        ("FDSE"),
        ("FELIX IDE"),
        ("ESI"),
        ("fido"),
        ("KIT-Fireball"),
        ("fouineur"),
        ("Freecrawl"),
        ("gammaSpider"),
        ("gazz"),
        ("gcreep"),
        ("golem"),
        ("googlebot"),
        ("griffon"),
        ("Gromit"),
        ("gulliver"),
        ("gulper"),
        ("hambot"),
        ("havIndex"),
        ("hotwired"),
        ("htdig"),
        ("iajabot"),
        ("INGRID/0.1"),
        ("Informant"),
        ("InfoSpiders"),
        ("inspectorwww"),
        ("irobot"),
        ("Iron33"),
        ("JBot"),
        ("jcrawler"),
        ("Teoma"),
        ("Jeeves"),
        ("jobo"),
        ("image.kapsi.net"),
        ("KDD-Explorer"),
        ("ko_yappo_robot"),
        ("label-grabber"),
        ("larbin"),
        ("legs"),
        ("Linkidator"),
        ("linkwalker"),
        ("Lockon"),
        ("logo_gif_crawler"),
        ("marvin"),
        ("mattie"),
        ("mediafox"),
        ("MerzScope"),
        ("NEC-MeshExplorer"),
        ("MindCrawler"),
        ("udmsearch"),
        ("moget"),
        ("Motor"),
        ("msnbot"),
        ("muncher"),
        ("muninn"),
        ("MuscatFerret"),
        ("MwdSearch"),
        ("sharp-info-agent"),
        ("WebMechanic"),
        ("combine"),
        ("NetScoop"),
        ("newscan-online"),
        ("ObjectsSearch"),
        ("Occam"),
        ("Orbsearch/1.0"),
        ("packrat"),
        ("pageboy"),
        ("ParaSite"),
        ("patric"),
        ("pegasus"),
        ("perlcrawler"),
        ("phpdig"),
        ("piltdownman"),
        ("Pimptrain"),
        ("pjspider"),
        ("PlumtreeWebAccessor"),
        ("PortalBSpider"),
        ("psbot"),
        ("Getterrobo"),
        ("-Plus"),
        ("Raven"),
        ("RHCS"),
        ("RixBot"),
        ("roadrunner"),
        ("Robbie"),
        ("robi"),
        ("RoboCrawl"),
        ("robofox"),
        ("Scooter"),
        ("Search-AU"),
        ("searchprocess"),
        ("Senrigan"),
        ("Shagseeker"),
        ("sift"),
        ("SimBot"),
        ("Site Valet"),
        ("skymob"),
        ("SLCrawler/2.0"),
        ("slurp"),
        ("ESI"),
        ("snooper"),
        ("solbot"),
        ("speedy"),
        ("spider_monkey"),
        ("SpiderBot/1.0"),
        ("spiderline"),
        ("nil"),
        ("suke"),
        ("http://www.sygol.com"),
        ("tach_bw"),
        ("TechBOT"),
        ("templeton"),
        ("titin"),
        ("topiclink"),
        ("UdmSearch"),
        ("urlck"),
        ("Valkyrie libwww-perl"),
        ("verticrawl"),
        ("Victoria"),
        ("void-bot"),
        ("Voyager"),
        ("VWbot_K"),
        ("crawlpaper"),
        ("wapspider"),
        ("WebBandit/1.0"),
        ("webcatcher"),
        ("T-H-U-N-D-E-R-S-T-O-N-E"),
        ("WebMoose"),
        ("webquest"),
        ("webreaper"),
        ("webs"),
        ("webspider"),
        ("WebWalker"),
        ("wget"),
        ("winona"),
        ("whowhere"),
        ("wlm"),
        ("WOLP"),
        ("WWWC"),
        ("none"),
        ("XGET"),
        ("Nederland.zoek"),
        ("AISearchBot"),
        ("woriobot"),
        ("NetSeer"),
        ("Nutch"),
        ("YandexBot")
        '
    );

    return $result;
}