CREATE TABLE IF NOT EXISTS `PREFIX_rkr_selled_plus`
(
    `id_slider`                     INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `name`                          varchar(64)      NOT NULL,
    `type`                          int(10) unsigned NOT NULL DEFAULT 1,
    `hook_name`                     varchar(64)               DEFAULT '',
    `period`                        varchar(64)      NOT NULL,
    `category_option`               int(10) unsigned,
    `id_categories`                 varchar(1024)    NOT NULL DEFAULT '',
    `manufacturer_option`           int(10) unsigned,
    `id_manufacturer`               int(10) unsigned NOT NULL DEFAULT 0,
    `max_products_show`             int(10) unsigned,
    `image_type`                    varchar(64)      NOT NULL,
    `columns_xl`                    int(10) unsigned NOT NULL DEFAULT 4,
    `columns_lg`                    int(10) unsigned NOT NULL DEFAULT 3,
    `columns_md`                    int(10) unsigned NOT NULL DEFAULT 2,
    `columns_sm`                    int(10) unsigned NOT NULL DEFAULT 1,
    `autoplay`                      tinyint(1)       NOT NULL DEFAULT '0',
    `loop`                          tinyint(1)       NOT NULL DEFAULT '0',
    `lazy`                          tinyint(1)       NOT NULL DEFAULT '0',
    `show_product_name`             tinyint(1)       NOT NULL DEFAULT '1',
    `show_product_category`         tinyint(1)       NOT NULL DEFAULT '0',
    `show_add_to_cart`              tinyint(1)       NOT NULL DEFAULT '0',
    `show_price`                    tinyint(1)       NOT NULL DEFAULT '0',
    `show_displayProductPriceBlock` tinyint(1)       NOT NULL DEFAULT '0',
    `show_product_variants`         tinyint(1)       NOT NULL DEFAULT '0',
    `show_product_flags`            tinyint(1)       NOT NULL DEFAULT '0',
    `show_product_quick_view`       tinyint(1)       NOT NULL DEFAULT '0',
    `rem_size_title`                float(5)         NOT NULL DEFAULT 1.3125,
    `rem_size_product_name`         float(5)         NOT NULL DEFAULT 0.875,
    `rem_size_product_category`     float(5)         NOT NULL DEFAULT 1.125,
    `rem_size_product_price`        float(5)         NOT NULL DEFAULT 1,
    `default_style`                 tinyint(1)       NOT NULL DEFAULT 1,
    `filter_page_visibility`        tinyint(1)       NOT NULL DEFAULT 0,
    `page_index`                    tinyint(1)       NOT NULL DEFAULT 1,
    `page_product`                  tinyint(1)       NOT NULL DEFAULT 1,
    `page_category`                 tinyint(1)       NOT NULL DEFAULT 1,
    `filter_id_categories`          varchar(1024)    NOT NULL DEFAULT '',
    `page_addresses`                tinyint(1)       NOT NULL DEFAULT 1,
    `page_manufacturer`             tinyint(1)       NOT NULL DEFAULT 1,
    `filter_id_manufacturer`        int(10) unsigned NOT NULL DEFAULT 0,
    `page_supplier`                 tinyint(1)       NOT NULL DEFAULT 1,
    `page_cms`                      tinyint(1)       NOT NULL DEFAULT 1,
    `page_cart`                     tinyint(1)       NOT NULL DEFAULT 1,
    `page_my_account`               tinyint(1)       NOT NULL DEFAULT 1,
    `page_sitemap`                  tinyint(1)       NOT NULL DEFAULT 1,
    `active`                        tinyint(1)       NOT NULL DEFAULT '1',
    `position`                      int(10) unsigned NOT NULL DEFAULT '0',
    PRIMARY KEY (`id_slider`),
    KEY (`name`)
) ENGINE = ENGINE_TYPE
  DEFAULT CHARSET = 'utf8';
CREATE TABLE IF NOT EXISTS `PREFIX_rkr_selled_plus_lang`
(
    `id_slider` INTEGER UNSIGNED NOT NULL,
    `id_lang`   INTEGER UNSIGNED NOT NULL,
    `title`     varchar(128)     NOT NULL,
    PRIMARY KEY (`id_slider`, `id_lang`),
    KEY `id_lang` (`id_lang`)
) ENGINE = ENGINE_TYPE
  DEFAULT CHARSET = 'utf8';